# Generated by Django 2.2 on 2020-10-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies_name', models.CharField(max_length=200)),
                ('hobbies_type', models.CharField(max_length=2000)),
            ],
        ),
    ]
