# Generated by Django 2.2 on 2020-10-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hobbies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='hobbie_photo',
            field=models.CharField(default='https://i.ytimg.com/vi/Tz7EwqQFhjk/maxresdefault.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='hobbies_type',
            field=models.CharField(max_length=200),
        ),
    ]
